name: 'Baba Is Commit'
description: 'Baba Is You 컨셉의 깃허브 기여도 SVG 애니메이션을 생성합니다.'
branding:
  icon: 'activity'
  color: 'white'

inputs:
  github_user_name:
    description: 'SVG를 생성할 깃허브 유저 이름'
    required: true
  github_token:
    description: '기여도 데이터를 읽어오기 위한 GitHub Token'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'