name: Update Baba Is Commit

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: package installation
        run: npm install
        
      - name: baba SVG generation
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: |
          npm run build
          node dist/index.js
          
      - name: Commit and push SVG to 'baba-output' branch
        run: |
          # Create a new directory for the output SVG
          mkdir -p output
          mv baba-is-commit.svg output/
          cd output

          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b baba-output
          git add baba-is-commit.svg
          git commit -m "BABA IS COMMIT - Update SVG"
          
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" baba-output
